option(PGO_BUILD_TESTS "Build pgo tests" ON)
option(PGO_BUILD_EXAMPLES "Build pgo examples" ON)
option(PGO_BUILD_TOOLS "Build pgo command-line tools" ON)
option(PGO_BUILD_BENCHMARKS "Build pgo benchmarks" ON)
option(PGO_BUILD_C_API "Build C99 shared-library API" ON)
option(PGO_BUILD_PYTHON "Build the nanobind Python extension" OFF)
option(PGO_ENABLE_PYTHON_STABLE_ABI "Build Python extension with Python stable ABI when supported" OFF)
option(PGO_ENABLE_SANITIZERS "Enable address and undefined behavior sanitizers" OFF)
option(PGO_WARNINGS_AS_ERRORS "Treat warnings as errors" OFF)
option(PGO_ENABLE_GPU "Enable Vulkan/Slang GPU backend targets" OFF)
option(PGO_ENABLE_SPDLOG "Enable spdlog-backed pgo::log sink" OFF)
option(PGO_ENABLE_ALEMBIC "Enable Alembic .abc export support" OFF)
option(PGO_ENABLE_EIGEN_ACCELERATION "Enable Eigen BLAS/LAPACK acceleration" OFF)

set(PGO_PYTHON_EXTENSION_NAME "_pgo_ext" CACHE STRING "Name of the private Python extension module")
set_property(CACHE PGO_PYTHON_EXTENSION_NAME PROPERTY STRINGS "_pgo_ext")

set(PGO_EIGEN_ACCELERATION_BACKEND "AUTO" CACHE STRING "Eigen acceleration backend: AUTO, MKL, ACCELERATE, NONE")
set_property(CACHE PGO_EIGEN_ACCELERATION_BACKEND PROPERTY STRINGS AUTO MKL ACCELERATE NONE)
