name: ci

on:
  push:
  pull_request:

jobs:
  build-debug:
    name: ${{ matrix.os }} debug
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - name: Install Conan
        run: pipx install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Install dependencies
        run: conan install . --output-folder=build/conan/debug --build=missing -s build_type=Debug

      - name: Configure
        run: cmake --preset debug

      - name: Build
        run: cmake --build --preset debug

  sanitize:
    name: ubuntu asan-ubsan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - name: Install Conan
        run: pipx install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Install dependencies
        run: conan install . --output-folder=build/conan/debug --build=missing -s build_type=Debug

      - name: Configure
        run: cmake --preset asan

      - name: Build
        run: cmake --build --preset asan
